### ISSUE TITLE
sklearn is installed, but... ModuleNotFoundError: No module named 'sklearn'

### ISSUE THREAD

**Issue by lucajovine** [atomoton/ensemblator#30]
\> pip install ensemblator
Collecting ensemblator
  Downloading ensemblator-4.0.0-py3-none-any.whl (37 kB)
Collecting sklearn
  Downloading sklearn-0.0.post1.tar.gz (3.6 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: scipy in /usr/local/conda/miniconda3/lib/python3.10/site-packages (from ensemblator) (1.10.0)
Requirement already satisfied: matplotlib in /usr/local/conda/miniconda3/lib/python3.10/site-packages (from ensemblator) (3.6.3)
Requirement already satisfied: biopython in /usr/local/conda/miniconda3/lib/python3.10/site-packages (from ensemblator) (1.80)
Requirement already satisfied: numpy in /usr/local/conda/miniconda3/lib/python3.10/site-packages (from ensemblator) (1.24.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/conda/miniconda3/lib/python3.10/site-packages (from matplotlib->ensemblator) (4.38.0)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/local/conda/miniconda3/lib/python3.10/site-packages (from matplotlib->ensemblator) (3.0.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/conda/miniconda3/lib/python3.10/site-packages (from matplotlib->ensemblator) (23.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/conda/miniconda3/lib/python3.10/site-packages (from matplotlib->ensemblator) (1.4.4)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/conda/miniconda3/lib/python3.10/site-packages (from matplotlib->ensemblator) (1.0.7)
Requirement already satisfied: cycler>=0.10 in /usr/local/conda/miniconda3/lib/python3.10/site-packages (from matplotlib->ensemblator) (0.11.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/conda/miniconda3/lib/python3.10/site-packages (from matplotlib->ensemblator) (2.8.2)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/conda/miniconda3/lib/python3.10/site-packages (from matplotlib->ensemblator) (9.4.0)
Requirement already satisfied: six>=1.5 in /usr/local/conda/miniconda3/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib->ensemblator) (1.16.0)
Building wheels for collected packages: sklearn
  Building wheel for sklearn (setup.py) ... done
  Created wheel for sklearn: filename=sklearn-0.0.post1-py3-none-any.whl size=2935 sha256=fb71aa96827977a791c3d1b92fe63b9c94d8154839593f0c39d8a8f1b4bb4963
  Stored in directory: /Users/luca/Library/Caches/pip/wheels/c5/88/35/cc8a1e198b27a1d3d9d3f9b30090b9d5531778847835472ec4
Successfully built sklearn
Installing collected packages: sklearn, ensemblator
Successfully installed ensemblator-4.0.0 sklearn-0.0.post1

\> ensemblator
Traceback (most recent call last):
  File "/usr/local/conda/miniconda3/bin/ensemblator", line 5, in <module>
    from ensemblator.ensemblator_cli import main
  File "/usr/local/conda/miniconda3/lib/python3.10/site-packages/ensemblator/ensemblator_cli.py", line 2, in <module>
    from ensemblator.ensemblator_core import *
  File "/usr/local/conda/miniconda3/lib/python3.10/site-packages/ensemblator/ensemblator_core.py", line 16, in <module>
    from sklearn.cluster import AffinityPropagation
ModuleNotFoundError: No module named 'sklearn'

**Comment by lucajovine** [comment]
With:

\> echo $PYTHONPATH
/usr/local/conda/miniconda3/lib/python3.10/site-packages:

and:

\> ls -l /usr/local/conda/miniconda3/lib/python3.10/site-packages/sklearn-0.0.post1.dist-info/
total 20
-rw-r--r-- 1 luca luca    4 Mar  6 19:29 INSTALLER
-rw-r--r-- 1 luca luca 3437 Mar  6 19:29 METADATA
-rw-r--r-- 1 luca luca  529 Mar  6 19:29 RECORD
-rw-r--r-- 1 luca luca   14 Mar  6 19:29 top_level.txt
-rw-r--r-- 1 luca luca   92 Mar  6 19:29 WHEEL
